### ISSUE TITLE
Comply with maven standard directory layout

### ISSUE THREAD

**Issue by physikerwelt** [ContemporaryArtwork/M-to-m#1]
See
http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
i.e. move test resources to the test resource folder

**Comment by physikerwelt** [comment]
I suggest you start here.

**Comment by ContemporaryArtwork** [comment]
got it

**Comment by physikerwelt** [comment]
This file is not needed:
https://github.com/ContemporaryArtwork/M-to-m/blob/master/src/main/resources/junit-4.10.jar
This is not a java source file
https://github.com/ContemporaryArtwork/M-to-m/blob/master/src/main/java/KLSadd.tex
...
name your package e.g. com.contemporaryartwork.m-to-m ...
and move the files to .../com/contemporaryartwork/m-to-m/main.java ...

**Comment by ContemporaryArtwork** [comment]
" name your package e.g. com.contemporaryartwork.m-to-m ...
and move the files to .../com/contemporaryartwork/m-to-m/main.java ..."
how do I go about doing this?

**Comment by ContemporaryArtwork** [comment]
Is this finished now or am I missing something?

**Comment by physikerwelt** [comment]
it looks slightly better.
Please have a look at
http://www.iwombat.com/standards/JavaStyleGuide.html

**Comment by HowardCohl** [comment]
@physikerwelt @ContemporaryArtwork 

Should this issue be closed?

If not, can we outline what must be completed before it is closed?

**Comment by physikerwelt** [comment]
I think it's not done.
Explain why each file complies with
http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
The two main programs are in the main directory, and the test method is in the test directory, additionally the main and test resources (KLSadd.tex) are both in their respective resource directories.
All the needed folders are there and go according to the layout you sent.

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
Should this issue be closed now, or is there something that I'm missing?

**Comment by physikerwelt** [comment]
How do you differentiate between a main and a test program. Usually test programs are junit tests or similar tests.

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
The files in my test directory were all test classes

**Comment by physikerwelt** [comment]
Ah ok I see. The 1 file. However, this is not a real test because it just tests if your program does something. But it does not test if your program does the right thing. Have a look into JUnit tests in the literature.
