### ISSUE TITLE
mvn exec

### ISSUE THREAD

**Issue by physikerwelt** [ContemporaryArtwork/M-to-m#2]
support mvn exec
http://www.mojohaus.org/exec-maven-plugin/usage.html
I.e.
```
 mvn exec:java -input=./filename.txt
```
shoud replace all m by in the file ./filename

See also
https://github.com/TU-Berlin/mathosphere/tree/master/restd

**Comment by HowardCohl** [comment]
@physikerwelt @ContemporaryArtwork 

Should this issue be closed?

If not, can we outline what must be completed before it is closed?

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
This issue is probably the most troubling one. I have never written in xml format before so when I try to write a pom.xml I get pretty confused. I've checked all the links you've sent and I still can't really make sense of the pom.xml layout. Are there any more basic references so a beginner to xml can know what's happening?

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
Wait wait wait, I think I figured it out.
I have configured the pom.xml so that passing mvn exec:java -Dinput="filename" runs MConvertStream on any file in "src/main/resources". Is this okay now or do I have to make it do something different?

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
Should this issue be closed now, or is there something that I'm missing?

**Comment by physikerwelt** [comment]
Make it so that any valid filename can be used

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
What do you mean by any valid filename?

**Comment by physikerwelt** [comment]
I mean any file in your file system that exists and where you have read permission

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
So basically just remove the /src/main/resource part in the pom so the user can specify the path?
