### ISSUE TITLE
Write a test for edge cases

### ISSUE THREAD

**Issue by physikerwelt** [ContemporaryArtwork/M-to-m#3]
Write a test that tests for the input
```
{&-}
```

**Comment by HowardCohl** [comment]
@physikerwelt @ContemporaryArtwork 

Should this issue be closed?

If not, can we outline what must be completed before it is closed?

**Comment by physikerwelt** [comment]
To close this issue there should be at least on junit test that tests if the input
```
{&-}
```
returns the outptu
```
{&-}
```

**Comment by ContemporaryArtwork** [comment]
So a test that has a file with {&-} in it to determine if the {&-} will be left at the end?

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
I'm going to replace the {&-] with a random UUID from "java.util.UUID" so it can run without having to deal with any common arrangements of characters. Is this okay?

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
Should this issue be closed now, or is there something that I'm missing?

**Comment by physikerwelt** [comment]
You normally close issues by committing code that resolves the issue.
In your commit message you would write
close #3
that way others can trace if you actually implement what you describe.

**Comment by ContemporaryArtwork** [comment]
Ok, did not know that, thanks
