### ISSUE TITLE
Test code should call main clases

### ISSUE THREAD

**Issue by physikerwelt** [ContemporaryArtwork/M-to-m#4]
Currently the test-code is independent of the main code.
The test classes should use the code of the main program.

**Comment by HowardCohl** [comment]
@physikerwelt Normally in one of the GitHub repositories I work with, I can edit a post that I didn't write.  But for some reason, I can't do that here. Why is that?  Do I have to be added somehow?

**Comment by physikerwelt** [comment]
@HowardCohl you can do that only in repositories you own. This repo is owned by @ContemporaryArtwork . He is the only person that can assign rights and change permissions.

**Comment by HowardCohl** [comment]
@physikerwelt So it's possible for @ContemporaryArtwork  to assign me rights to edit issue posts?  @ContemporaryArtwork Can you do that for me?

**Comment by HowardCohl** [comment]
@ContemporaryArtwork Gracias.

**Comment by ContemporaryArtwork** [comment]
I added @HowardCohl  & @physikerwelt  to the collaborator list but I'm not sure if that fixes it.

**Comment by HowardCohl** [comment]
Seems like it fixed it. I already edited a post to improve English successfully. Great. (off topic) :)

**Comment by ContemporaryArtwork** [comment]
@physikerwelt Do you mean that the test code should be the same as the main code or the test methods should call the methods in the main code, or do you mean that the method in the test code should call the main method in the test code?

**Comment by physikerwelt** [comment]
the method in the test code should call the main method in the test code

**Comment by ContemporaryArtwork** [comment]
Gotcha

**Comment by physikerwelt** [comment]
In https://github.com/ContemporaryArtwork/M-to-m/blob/master/src/test/java/java/Test_one.java#L14-L18 you copy the relvant code.
The test should call the main program and test something unrelated to the main sources.

**Comment by ContemporaryArtwork** [comment]
what do you mean by "unrelated to the main sources"? Should I have the test method do something not related to the program itself, like print "hello world"?

**Comment by physikerwelt** [comment]
oh sorry I missed a not... I updated the comment.
...maybe you should read http://www.vogella.com/tutorials/JUnit/article.html which will demonstrate what's the benefit of unit tests. Afterwards you should fix #1 ... this will also simplify this issue

**Comment by ContemporaryArtwork** [comment]
I think I did what you asked for. I will read the link once I have enough time, very busy at the moment.

**Comment by HowardCohl** [comment]
@physikerwelt @ContemporaryArtwork 

Should this issue be closed?

If not, can we outline what must be completed before it is closed?

**Comment by physikerwelt** [comment]
@HowardCohl It's hard to say currently the test code does not even compile.
@ContemporaryArtwork Please make sure that the travis tests don't fail
https://travis-ci.org/ContemporaryArtwork/M-to-m

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
Sorry, I messed up the pom.xml before. I fixed it.

**Comment by physikerwelt** [comment]
This issue is fixed. However, you can not refer to /home/travis in your tests since that would work only in the travis ci system

**Comment by HowardCohl** [comment]
@ContemporaryArtwork
 
Just curious, what did you replace /home/travis with?

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
Is there a way to tell if the program is running on travis ci?
Also, how would I go about getting the test to run on travis ci without refering to /home/travis/?

@HowardCohl 
I just put the full path of the file into the test method so that MConvertStream could be ran without 
messing up because /home/travis/ didn't exist on a system other than travis ci.
